version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    env_file:
      - .env # Load environment variables from .env file
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bitcoin_user
      POSTGRES_PASSWORD: bitcoin_password
      POSTGRES_DB: bitcoin_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: